package greendao.datebase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.sqlitedemo.Student;
import com.example.administrator.sqlitedemo.Teach;

import greendao.datebase.StudentDao;
import greendao.datebase.TeachDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig teachDaoConfig;

    private final StudentDao studentDao;
    private final TeachDao teachDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teachDaoConfig = daoConfigMap.get(TeachDao.class).clone();
        teachDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        teachDao = new TeachDao(teachDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Teach.class, teachDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        teachDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeachDao getTeachDao() {
        return teachDao;
    }

}
